# This job is used to stop Helm from managing resources without deleting them.
apiVersion: batch/v1
kind: Job
metadata:
  name: kotsadm-abandon-resources
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "2"
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "admin-console.labels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          if kubectl get configmap kotsadm-confg -n {{ .Release.Namespace }} -o jsonpath='{.metadata.labels.app\.kubernetes\.io/managed-by}' | grep -q "Helm"; then
            kubectl annotate configmap kotsadm-confg -n {{ .Release.Namespace }} helm.sh/resource-policy=keep
          fi
          if kubectl get configmap kotsadm-application-metadata -n {{ .Release.Namespace }} -o jsonpath='{.metadata.labels.app\.kubernetes\.io/managed-by}' | grep -q "Helm"; then
            kubectl annotate configmap kotsadm-application-metadata -n {{ .Release.Namespace }} helm.sh/resource-policy=keep
          fi
        image: {{ .Values.images.kotsadm }}
        imagePullPolicy: IfNotPresent
        name: abandon-resources
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: OnFailure
      serviceAccountName: kotsadm
