{{ if .Values.minimalRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: kotsadm-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
{{ end }}