apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: {{ include "admin-console.fullname" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 3000
  selector:
    app: kotsadm
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
