{{ if .Values.kurlProxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kurl-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    kots.io/kotsadm: "true"
    kots.io/backup: velero
    {{- include "admin-console.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: secret-manager
  labels:
    kots.io/kotsadm: "true"
    kots.io/backup: velero
    {{- include "admin-console.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kurl-proxy-tls-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    kots.io/kotsadm: "true"
    kots.io/backup: velero
    {{- include "admin-console.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager
subjects:
- kind: ServiceAccount
  name: kurl-proxy
  namespace: {{ .Release.Namespace }}
{{ end }}
