{{- if .Values.kurlProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kurl-proxy-kotsadm
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: kurl-proxy-kotsadm
  ports:
  - name: http
    port: {{ .Values.kurlProxy.targetPort }}
    targetPort: {{ .Values.kurlProxy.targetPort }}
{{- if .Values.kurlProxy.nodePort }}
    nodePort: {{ .Values.kurlProxy.nodePort }}
{{- end}}
{{- end }}
