{{ if not .Values.isHelmManaged }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: kotsadm-postgres
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  selector:
    app: kotsadm-postgres
  type: ClusterIP
status:
  loadBalancer: {}
{{ end }}