{{ if not .Values.isHelmManaged }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kotsadm-rqlite
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: kotsadm-rqlite-headless
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: kotsadm-rqlite
  volumeClaimTemplates:
  - metadata:
      name: kotsadm-rqlite
      labels:
        {{- include "admin-console.labels" . | nindent 8 }}
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        app: kotsadm-rqlite
        {{- include "admin-console.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      volumes:
      - name: authconfig
        secret:
          secretName: kotsadm-rqlite
          items:
          - key: authconfig.json
            path: authconfig.json
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - kotsadm-rqlite
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: {{ .Values.images.rqlite }}
        name: rqlite
        args:
        - -disco-mode=dns
        - -disco-config={"name":"kotsadm-rqlite-headless"}
        - -bootstrap-expect=1
        - -auth=/auth/config.json
        - -join-as=kotsadm
        ports:
        - name: rqlite
          containerPort: 4001
        volumeMounts:
        - name: kotsadm-rqlite
          mountPath: /rqlite/file
        - name: authconfig
          mountPath: /auth/config.json
          subPath: authconfig.json
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /readyz
            port: rqlite
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readyz
            port: rqlite
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
{{ end }}
