apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: kotsadm-password
data:
  passwordBcrypt: {{ default "password" .Values.adminConsole.password | bcrypt | b64enc }}