{{- $rqlitePassword := uuidv4 }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "kotsadm-rqlite") }}
{{- if $secret }}
{{- $rqlitePassword = index $secret.data "password" | b64dec }}
{{- end -}}
{{- $rqliteUri := printf "http://kotsadm:%s@kotsadm-rqlite.%s.svc.cluster.local:4001?timeout=120&disableClusterDiscovery=true" $rqlitePassword .Release.Namespace }}
{{- $rqliteAuthConfig := printf `[{"username": "kotsadm", "password": "%s", "perms": ["all"]}, {"username": "*", "perms": ["status", "ready"]}]` $rqlitePassword }}
apiVersion: v1
kind: Secret
metadata:
  name: kotsadm-rqlite
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
stringData:
  uri: {{ $rqliteUri | quote }}
  password: {{ $rqlitePassword | quote }}
  authconfig.json: {{ $rqliteAuthConfig | quote }}
