# Default password is "password".
# Password specified in values or on command line overrides password currently in secret.
# If no password is specified, password in secret is preserved.
# If passwordSecretRef is defined this will be skipped entirely (useful for EC)
{{- if not .Values.passwordSecretRef }}
{{- $passwordBcrypt := "password" | bcrypt | b64enc }}
{{- if ne .Values.password "" }}
{{-   $passwordBcrypt = .Values.password | bcrypt | b64enc  }}
{{- else -}}
{{-   $secret := (lookup "v1" "Secret" .Release.Namespace "kotsadm-password") }}
{{-   if $secret }}
{{-     $passwordBcrypt = index $secret.data "passwordBcrypt" }}
{{-   end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: kotsadm-password
data:
  passwordBcrypt: {{ $passwordBcrypt }}
{{- end }}
