{{- $clusterToken := uuidv4 }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "kotsadm-cluster-token") }}
{{- if $secret }}
{{- $clusterToken = index $secret.data "kotsadm-cluster-token" | b64dec }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: kotsadm-cluster-token
  annotations:
    "helm.sh/resource-policy": "keep"
stringData:
  kotsadm-cluster-token: {{ $clusterToken }}
