{{ if not .Values.isHelmManaged }}
{{- $rqlitePassword := uuidv4 }}
{{- $rqliteUri := printf "http://kotsadm:%s@kotsadm-rqlite:4001?level=strong&timeout=10" $rqlitePassword }}
{{- $rqliteAuthConfig := printf "[{\"username\": \"kotsadm\", \"password\": \"%s\", \"perms\": [\"all\"]}, {\"username\": \"*\", \"perms\": [\"status\", \"ready\"]}]" $rqlitePassword }}
{{- $rqlitePasswordb64 := $rqlitePassword | b64enc | quote }}
{{- $rqliteUrib64 := $rqliteUri | b64enc | quote }}
{{- $rqliteAuthConfigb64 := $rqliteAuthConfig | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "kotsadm-rqlite") }}
{{- if $secret }}
{{- $rqlitePasswordb64 = index $secret.data "password" }}
{{- $rqliteUrib64 = index $secret.data "uri" }}
{{- $rqliteAuthConfigb64 = index $secret.data "authconfig.json" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: kotsadm-rqlite
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
data:
  uri: {{ $rqliteUrib64 }}
  password: {{ $rqlitePasswordb64 }}
  authconfig.json: {{ $rqliteAuthConfigb64 }}
{{ end }}
