name: 'KOTS E2E'
description: 'Composite action for running KOTS e2e test'
inputs:
  test-name:
    description: 'Individual test to run'
    required: true
  replicated-api-token:
    description: 'Replicated API token for C11y matrix'
    required: false
runs:
  using: "composite"
  steps:
    - name: Create Cluster 
      id: create-cluster 
      uses: replicatedhq/replicated-actions/create-cluster@v1 
      with:
        api-token: ${{ inputs.replicated-api-token }}
        kubernetes-distribution: kind
        kubernetes-version: v1.28.0
        cluster-name: automated-kots-helm-${{ github.run_id }}-${{ inputs.test-name }}
        timeout-minutes: '120'
        ttl: 2h
        export-kubeconfig: true

    - name: Run test
      working-directory: e2e/${{ inputs.test-name }}
      env:
        CHART_URL: oci://ttl.sh/automated-${{ github.run_id }}/admin-console
        CHART_VERSION: 0.0.0-main
      run: ./run.sh
      shell: bash

    - name: Generate support bundle on failure
      if: failure()
      uses: ./.github/actions/generate-support-bundle
      with:
        artifact-name: ${{ inputs.test-name }}-${{ github.run_id }}-support-bundle

    - name: Remove Cluster
      id: remove-cluster
      uses: replicatedhq/replicated-actions/remove-cluster@v1
      if: ${{ always() && steps.create-cluster.outputs.cluster-id != '' }}
      continue-on-error: true
      with:
        api-token: ${{ inputs.replicated-api-token }}
        cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}
