name: Pull request
on:
- pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: ttl.sh
      env:
        GITHUB_USER: automated-${{ github.run_id }}
      run: make build-ttl.sh

  e2e:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        test:
        - s3-to-rqlite
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: ./.github/actions/e2e
      secrets: inherit
      with:
        test-name: ${{ matrix.test }}
        replicated-api-token: ${{ secrets.C11Y_MATRIX_TOKEN }}
