name: Pull request
on:
- pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      chart-path: ${{ steps.build.outputs.chart-path }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: build local
      id: build
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        export KOTS_TAG=$(gh release view --repo replicatedhq/kots --json tagName -q .tagName)
        make build
        echo "chart-path=${{ github.workspace }}/admin-console-${KOTS_TAG#v}.tgz" >> "$GITHUB_OUTPUT"

  e2e:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        test:
        - s3-to-rqlite
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: ./.github/actions/e2e
      with:
        test-name: ${{ matrix.test }}
        chart-path: ${{ needs.build.outputs.chart-path }}
        replicated-api-token: ${{ secrets.C11Y_MATRIX_TOKEN }}

  # this job will validate that all the tests passed
  # it is used for the github branch protection rule
  validate-success:
    runs-on: ubuntu-20.04
    needs:
      - e2e
    if: always()
    steps:
      # https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context
      - name: fail if e2e job was not successful
        if: needs.e2e.result != 'success'
        run: exit 1
      - name: succeed if everything else passed
        run: echo "Validation succeeded"
