name: Pull request
on:
- pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: ttl.sh
      env:
        GITHUB_USER: automated-${{ github.run_id }}
      run: make build-ttl.sh

  e2e:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        test:
        - s3-to-rqlite
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run test
      working-directory: e2e/${{ matrix.test }}
      env:
        CHART_URL: oci://ttl.sh/automated-${{ github.run_id }}/admin-console
        CHART_VERSION: 0.0.0-main
      run: ./run.sh
